### ISSUE TITLE
IRecipe doesn't respect the input(s) when it's necessary

### ISSUE THREAD

**Issue by 3TUSK** [zmaster587/libVulpes#10]
@forestbat said he lost all his upgrades on his draconic evolution armor after passing it into the chemical reactor (from Advanced Rocketry, obviously). I did a bit research on this, and finally found the following:
By doing [this](https://github.com/zmaster587/AdvancedRocketry/blob/RoundPlanets7_10/src/main/java/zmaster587/advancedRocketry/tile/multiblock/machine/TileChemicalReactor.java#L54-L57), a new ItemStack of armor with space protection enchantment is returned, rather than the actual input ItemStack with the enchantment, when passing a piece of armor into the machine.
The problem is that, the interface [`zmaster587.libVulpes.interfaces.IRecipe`](https://github.com/zmaster587/libVulpes/blob/master/src/main/java/zmaster587/libVulpes/interfaces/IRecipe.java) has no capability to do so - we cannot fetch the actual input via this interface only. Reflection doesn't really help, as that may require to get the caller instance, which... is not feasible at all. 

I am not sure if it's intended or indeed a design flaw, and understand that changing it will break tones of stuff, so I decide to open this issue first.
> Yes, we could just hardcode this logic for chemical reactor only, but... what if there are actually more use cases?

**Comment by 3TUSK** [comment]
For @forestbat - passing your armor to the chemical reactor first, as current workaround. Also, try avoiding doing this for your something like blood magic armors, if any.

**Comment by zmaster587** [comment]
It's more a design flaw.  In order to be able to handle arbitrary input and outputs which may include fluid and often have a completely different output item than input items, it was much easier just to keep track of the given inputs and outputs.

Considering this is the only planned recipe of this type, the easiest way to go would be to hardcode the chemical reactor.  If this type of recipe does end up getting used later on, very little effort would be lost I think.

**Comment by 3TUSK** [comment]
I guess at least https://github.com/zmaster587/AdvancedRocketry/commit/02ffbed265cb3225ccb2ea2a16afc006c13e1358 solves the issue right now... closing. Reopen when necessary.
